### ISSUE TITLE
Prepare the repo for the big split

### ISSUE THREAD

**Issue by ripel2** [EngineSquared/EngineSquared#54]
One of our goals is to split our repository's code in multiple submodules for different purposes. This is inspired by the [raylib architecture](https://github.com/raysan5/raylib/wiki/raylib-architecture)
Right now the part we want to separate from the rest is the vk-wrapper, which has a lot of boilerplate code needed for the pipeline to work properly.

This issue is about preparing the main repository to handle usage of submodules.
For now the vk-wrapper code should stay inside this repository but in a new folder.

We also need to consider the fact that this project is still an Epitech Innovative Project and that every file should be present on Epitech's delivery repository.

TODO:
- [ ]  Separate the build of the engine's core components (registry, entity...) and plugins (vk-vrapper...)
- [ ]  Move the vk-wrapper in a new folder (only the vk-wrapper for now)
- [ ]  Add a job in the CI that can (somehow) recursively clone the submodules and push the files to Epitech's repository

**Comment by Miou-zora** [comment]
Do we need to add all plugins and make them works together in Epitech's repository, or do we want to push all of our codebase (core and plugins) without making them working thogether (the core will work tho) ?
